pr: none

jobs:
- job: fats

  strategy:
    matrix:
      minikube:
        imageName: ubuntu-16.04
        qualifier: daemon
        cluster: minikube
        registry: docker-daemon
      dockerhub:
        imageName: ubuntu-16.04
        qualifier: minikube
        cluster: minikube
        registry: dockerhub
      gke:
        imageName: ubuntu-16.04
        qualifier: gke
        cluster: gke
        registry: gcr
      pks:
        imageName: ubuntu-16.04
        qualifier: pks
        cluster: pks-gcp
        registry: gcr
      windows:
        imageName: windows-2019
        qualifier: windows
        cluster: gke
        registry: gcr

  timeoutInMinutes: 90

  pool:
    vmImage: $(imageName)

  variables:
    CLUSTER:  '$(cluster)'
    REGISTRY: '$(registry)'
    CLUSTER_NAME: 'fats-$(Build.BuildId)-$(qualifier)'
    NAMESPACE: '$(CLUSTER_NAME)'

  steps:

  - task: DownloadSecureFile@1
    inputs:
      secureFile: toolsmiths-oakland.json
    condition: and(succeeded(), eq(variables['CLUSTER'], 'pks-gcp'))
    displayName: 'Load credentials'

  - bash: ./ci/run.sh
    env:
      DOCKER_USERNAME: '$(DockerUsername)'
      DOCKER_PASSWORD: '$(DockerPassword)'
      GCLOUD_CLIENT_SECRET: '$(GcloudClientSecret)'
      PIVNET_REFRESH_TOKEN: '$(PivnetRefreshToken)'
    displayName: 'Run FATS'

  - template: ci/dump-diagnostics-steps.yml

  - bash: ./ci/cleanup.sh
    env:
      DOCKER_USERNAME: '$(DockerUsername)'
      DOCKER_PASSWORD: '$(DockerPassword)'
      GCLOUD_CLIENT_SECRET: '$(GcloudClientSecret)'
      PIVNET_REFRESH_TOKEN: '$(PivnetRefreshToken)'
    condition: always()
    displayName: 'Cleanup FATS'
